spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true

  jpa:
    database: H2
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop

